### ISSUE TITLE
Python - Project logging setup 

### ISSUE THREAD

**Issue by saifurrehman4114** [alexanderp99/RAG-enhanced-local-LLM#1]
1. Update the config.yaml file:
```
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app.log
loggers:
  "":  # Root logger
    level: DEBUG
    handlers: [console, file]
  # Set higher log levels for third-party libraries
  urllib3:
    level: WARNING
  chromadb:
    level: WARNING
```
2. Update the logger_config.py file:

```
import logging
import logging.config
import os
import yaml

DEFAULT_CONFIG_FILE = 'config.yaml'

def get_project_path():
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def setup_logging(config_file_path=None) -> None:
    project_path = get_project_path()
    if config_file_path is None:
        config_file_path = DEFAULT_CONFIG_FILE
    config_path = os.path.join(project_path, config_file_path)
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Config file '{config_path}' not found.")
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)
    logging.config.dictConfig(config)

def get_logger(name):
    return logging.getLogger(name)

```

3. In your main application file (e.g., streamlitapp_with_Langgraph.py):

-   Add these lines at the top of the file:

  ```
  from configuration.logger_config import setup_logging, get_logger
  
  setup_logging()
  logger = get_logger(__name__)
  ```

- Replace print statements with logger calls:

  ```
# Instead of: print("Debug message")
  logger.debug("Debug message")
  
  # Instead of: print("Info message")
  logger.info("Info message")
```

4.  In other modules:

- Add this line at the top of each file:
  ```
  
  from configuration.logger_config import get_logger
    
    logger = get_logger(__name__)
  ```

- Use logger instead of print statements:

  ```
  # Instead of: print("Debug message")
  logger.debug("Debug message")
  
  ```

5. if you see unwanted debug messages from other libraries, add them to the config.yaml file under the "loggers" section, like this:
```
loggers:
  "":
    level: DEBUG
    handlers: [console, file]
  urllib3:
    level: WARNING
  chromadb:
    level: WARNING
  # Add other libraries here
  some_noisy_library:
    level: WARNING
```

**Comment by alexanderp99** [comment]
@saifurrehman4114 
Thank you for your quick response.

Are you sure this is the optimal way? For every library added I may have to add a statement.

I read here that libraries should not use the root logger in general. Is this true? An alternative would be to create a custom logger, that does not inherit from the root logger, correct?
[Wouldn't creating a ](https://stackoverflow.com/questions/35325042/python-logging-disable-logging-from-imported-modules)

**Comment by saifurrehman4114** [comment]
@alexanderp99 With these changes, you won't need to manually add statements for each library in your config file. If you do need to adjust the log level for a specific library, you can still do so in the config file, but it won't be necessary for most cases.

@alexanderp99 I've fixed the logging setup so that it now logs only debug messages from your modules, without showing debug statements from the external libraries. Please check if everything works as expected.

**If everything looks good, kindly proceed with the payment of $150 through Upwork.**


This approach does following things:
- Creates a custom logger that doesn't inherit from the root logger
- Avoids manual configuration for each third-party library
- Maintains a clean separation between your app's logging and third-party logging
- Provides a consistent way to get loggers across your application
- Sets a default WARNING level for all external libraries, reducing noise

1. Update the config.yaml file:
  ```
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: app.log
  loggers:
    your_app:  # Your application's logger
      level: DEBUG
      handlers: [console, file]
      propagate: False
    __main__:  # For the main script
      level: DEBUG
      handlers: [console, file]
      propagate: False
    # Default configuration for all other loggers (including third-party libraries)
    "":
      level: WARNING
      handlers: [console, file]
  ```
2. Update the logger_config.py file:

  ```
  import logging
  import logging.config
  import os
  import yaml
  
  DEFAULT_CONFIG_FILE = 'config.yaml'
  
  def get_project_path():
      return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
  
  def setup_logging(config_file_path=None) -> None:
      project_path = get_project_path()
      if config_file_path is None:
          config_file_path = DEFAULT_CONFIG_FILE
      config_path = os.path.join(project_path, config_file_path)
      if not os.path.exists(config_path):
          raise FileNotFoundError(f"Config file '{config_path}' not found.")
      with open(config_path, 'r') as f:
          config = yaml.safe_load(f)
      logging.config.dictConfig(config)
      
      # Set all existing loggers to WARNING level
      for logger_name in logging.root.manager.loggerDict:
          if logger_name not in config['loggers']:
              logging.getLogger(logger_name).setLevel(logging.WARNING)
  
  def get_logger(name):
      logger = logging.getLogger(f"your_app.{name}")
      logger.propagate = False  # Prevent propagation to parent loggers
      return logger
  ```

3. Usage in your main application and other modules:

  ```
  from configuration.logger_config import setup_logging, get_logger
  
  setup_logging()  # Call this once in your main script
  logger = get_logger(__name__)
  
  # Use logger as before
  logger.debug("Debug message")
  logger.info("Info message")
  ```
